-- ============================================================
-- Outlet Authority — EXPANDED manual seed (Phase 9b)
-- Apply in Supabase SQL editor (project uavbphkhomblzkjfuaot)
-- Safe / additive. Idempotent (ON CONFLICT DO UPDATE).
-- DR scores hand-curated from public Ahrefs / Moz / SimilarWeb data
-- (approximate, ±2). Re-run anytime to refresh the baseline.
-- ============================================================

insert into public.outlet_authority (domain, outlet_name, authority_score, source) values
  -- ========== US National news / wires ==========
  ('apnews.com',            'Associated Press',            93, 'manual'),
  ('npr.org',               'NPR',                         93, 'manual'),
  ('pbs.org',               'PBS',                         92, 'manual'),
  ('usatoday.com',          'USA Today',                   93, 'manual'),
  ('latimes.com',           'Los Angeles Times',           93, 'manual'),
  ('chicagotribune.com',    'Chicago Tribune',             92, 'manual'),
  ('bostonglobe.com',       'The Boston Globe',            91, 'manual'),
  ('sfchronicle.com',       'San Francisco Chronicle',     90, 'manual'),
  ('nydailynews.com',       'New York Daily News',         91, 'manual'),
  ('nypost.com',            'New York Post',               92, 'manual'),
  ('newsweek.com',          'Newsweek',                    92, 'manual'),
  ('time.com',              'TIME',                        93, 'manual'),
  ('theatlantic.com',       'The Atlantic',                92, 'manual'),
  ('newyorker.com',          'The New Yorker',             92, 'manual'),
  ('politico.com',          'Politico',                    91, 'manual'),
  ('thehill.com',           'The Hill',                    91, 'manual'),
  ('slate.com',             'Slate',                       91, 'manual'),
  ('salon.com',             'Salon',                       90, 'manual'),
  ('thedailybeast.com',     'The Daily Beast',             90, 'manual'),
  ('motherjones.com',       'Mother Jones',                89, 'manual'),
  ('thenation.com',         'The Nation',                  88, 'manual'),
  ('propublica.org',        'ProPublica',                  88, 'manual'),
  ('texastribune.org',      'The Texas Tribune',           82, 'manual'),
  ('semafor.com',           'Semafor',                     78, 'manual'),
  ('puck.news',             'Puck',                        72, 'manual'),
  ('thedispatch.com',       'The Dispatch',                72, 'manual'),
  ('thefp.com',             'The Free Press',              74, 'manual'),
  ('themessenger.com',      'The Messenger',               68, 'manual'),

  -- ========== US regional / metro dailies ==========
  ('seattletimes.com',      'The Seattle Times',           89, 'manual'),
  ('denverpost.com',        'The Denver Post',             88, 'manual'),
  ('startribune.com',       'Star Tribune',                87, 'manual'),
  ('dallasnews.com',        'The Dallas Morning News',     87, 'manual'),
  ('houstonchronicle.com',  'Houston Chronicle',           88, 'manual'),
  ('miamiherald.com',       'Miami Herald',                88, 'manual'),
  ('tampabay.com',          'Tampa Bay Times',             86, 'manual'),
  ('orlandosentinel.com',   'Orlando Sentinel',            86, 'manual'),
  ('ajc.com',               'The Atlanta Journal-Constitution', 89, 'manual'),
  ('philly.com',            'The Philadelphia Inquirer',   88, 'manual'),
  ('inquirer.com',          'The Philadelphia Inquirer',   88, 'manual'),
  ('baltimoresun.com',      'The Baltimore Sun',           86, 'manual'),
  ('post-gazette.com',      'Pittsburgh Post-Gazette',     85, 'manual'),
  ('cleveland.com',         'Cleveland.com',               86, 'manual'),
  ('detroitnews.com',       'The Detroit News',            85, 'manual'),
  ('freep.com',             'Detroit Free Press',          86, 'manual'),
  ('mercurynews.com',       'The Mercury News',            87, 'manual'),
  ('sandiegouniontribune.com','San Diego Union-Tribune',   85, 'manual'),
  ('azcentral.com',         'The Arizona Republic',        88, 'manual'),
  ('oregonlive.com',        'The Oregonian',               86, 'manual'),
  ('newsday.com',           'Newsday',                     86, 'manual'),
  ('charlotteobserver.com', 'The Charlotte Observer',      85, 'manual'),
  ('newsobserver.com',      'The News & Observer',         84, 'manual'),
  ('kansascity.com',        'The Kansas City Star',        84, 'manual'),
  ('stltoday.com',          'St. Louis Post-Dispatch',     84, 'manual'),
  ('courier-journal.com',   'The Courier-Journal',         83, 'manual'),
  ('tennessean.com',        'The Tennessean',              84, 'manual'),
  ('cincinnati.com',        'The Cincinnati Enquirer',     83, 'manual'),
  ('dispatch.com',          'The Columbus Dispatch',       83, 'manual'),
  ('omaha.com',             'Omaha World-Herald',          82, 'manual'),
  ('desmoinesregister.com', 'The Des Moines Register',     83, 'manual'),
  ('jsonline.com',          'Milwaukee Journal Sentinel',  83, 'manual'),
  ('chron.com',             'Houston Chronicle',           87, 'manual'),
  ('statesman.com',         'Austin American-Statesman',   83, 'manual'),
  ('expressnews.com',       'San Antonio Express-News',    82, 'manual'),

  -- ========== US TV / broadcast ==========
  ('nbcnews.com',           'NBC News',                    93, 'manual'),
  ('abcnews.go.com',        'ABC News',                    93, 'manual'),
  ('cbsnews.com',           'CBS News',                    93, 'manual'),
  ('foxnews.com',           'Fox News',                    93, 'manual'),
  ('foxbusiness.com',       'Fox Business',                88, 'manual'),
  ('msnbc.com',             'MSNBC',                       91, 'manual'),
  ('today.com',             'TODAY',                       89, 'manual'),
  ('cnbcafrica.com',        'CNBC Africa',                 70, 'manual'),
  ('marketwatch.com',       'MarketWatch',                 91, 'manual'),
  ('barrons.com',           'Barron''s',                   88, 'manual'),

  -- ========== UK / Ireland ==========
  ('independent.co.uk',     'The Independent',             93, 'manual'),
  ('mirror.co.uk',          'Daily Mirror',                92, 'manual'),
  ('dailymail.co.uk',       'Daily Mail',                  94, 'manual'),
  ('thesun.co.uk',          'The Sun',                     91, 'manual'),
  ('express.co.uk',         'Daily Express',               91, 'manual'),
  ('metro.co.uk',           'Metro',                       90, 'manual'),
  ('standard.co.uk',        'Evening Standard',            89, 'manual'),
  ('inews.co.uk',           'i News',                      85, 'manual'),
  ('itv.com',               'ITV News',                    91, 'manual'),
  ('sky.com',               'Sky News',                    91, 'manual'),
  ('news.sky.com',          'Sky News',                    89, 'manual'),
  ('channel4.com',          'Channel 4 News',              89, 'manual'),
  ('rte.ie',                'RTÉ',                         89, 'manual'),
  ('irishtimes.com',        'The Irish Times',             87, 'manual'),
  ('independent.ie',        'Irish Independent',           86, 'manual'),
  ('thejournal.ie',         'The Journal',                 84, 'manual'),
  ('belfasttelegraph.co.uk','Belfast Telegraph',           82, 'manual'),
  ('scotsman.com',          'The Scotsman',                84, 'manual'),
  ('heraldscotland.com',    'The Herald',                  82, 'manual'),
  ('walesonline.co.uk',     'Wales Online',                83, 'manual'),
  ('manchestereveningnews.co.uk','Manchester Evening News',85, 'manual'),
  ('liverpoolecho.co.uk',   'Liverpool Echo',              84, 'manual'),
  ('birminghammail.co.uk',  'Birmingham Mail',             83, 'manual'),
  ('thespectator.com',      'The Spectator',               85, 'manual'),
  ('newstatesman.com',      'New Statesman',               85, 'manual'),
  ('prospectmagazine.co.uk','Prospect',                    78, 'manual'),
  ('tortoisemedia.com',     'Tortoise',                    72, 'manual'),

  -- ========== Canada ==========
  ('cbc.ca',                'CBC',                         92, 'manual'),
  ('ctvnews.ca',            'CTV News',                    89, 'manual'),
  ('globalnews.ca',         'Global News',                 88, 'manual'),
  ('theglobeandmail.com',   'The Globe and Mail',          90, 'manual'),
  ('thestar.com',           'Toronto Star',                89, 'manual'),
  ('nationalpost.com',      'National Post',               87, 'manual'),
  ('macleans.ca',           'Maclean''s',                  82, 'manual'),
  ('lapresse.ca',           'La Presse',                   85, 'manual'),
  ('ledevoir.com',          'Le Devoir',                   80, 'manual'),
  ('thelogic.co',           'The Logic',                   62, 'manual'),
  ('betakit.com',           'BetaKit',                     65, 'manual'),

  -- ========== Australia / NZ ==========
  ('abc.net.au',            'ABC News (Australia)',        92, 'manual'),
  ('smh.com.au',            'The Sydney Morning Herald',   90, 'manual'),
  ('theage.com.au',         'The Age',                     89, 'manual'),
  ('news.com.au',           'news.com.au',                 92, 'manual'),
  ('theaustralian.com.au',  'The Australian',              87, 'manual'),
  ('afr.com',               'Australian Financial Review', 85, 'manual'),
  ('9news.com.au',          '9News',                       85, 'manual'),
  ('7news.com.au',          '7News',                       82, 'manual'),
  ('theguardian.com/au',    'The Guardian Australia',      88, 'manual'),
  ('crikey.com.au',         'Crikey',                      75, 'manual'),
  ('stuff.co.nz',           'Stuff',                       86, 'manual'),
  ('nzherald.co.nz',        'The New Zealand Herald',      87, 'manual'),
  ('rnz.co.nz',             'RNZ',                         84, 'manual'),

  -- ========== Europe ==========
  ('dw.com',                'Deutsche Welle',              91, 'manual'),
  ('spiegel.de',            'Der Spiegel',                 91, 'manual'),
  ('zeit.de',               'Die Zeit',                    90, 'manual'),
  ('faz.net',               'Frankfurter Allgemeine',      89, 'manual'),
  ('sueddeutsche.de',       'Süddeutsche Zeitung',         89, 'manual'),
  ('welt.de',               'Die Welt',                    89, 'manual'),
  ('bild.de',               'Bild',                        90, 'manual'),
  ('handelsblatt.com',      'Handelsblatt',                85, 'manual'),
  ('lemonde.fr',            'Le Monde',                    91, 'manual'),
  ('lefigaro.fr',           'Le Figaro',                   90, 'manual'),
  ('liberation.fr',         'Libération',                  87, 'manual'),
  ('lesechos.fr',           'Les Échos',                   85, 'manual'),
  ('france24.com',          'France 24',                   89, 'manual'),
  ('rfi.fr',                'RFI',                         87, 'manual'),
  ('elpais.com',            'El País',                     91, 'manual'),
  ('elmundo.es',            'El Mundo',                    89, 'manual'),
  ('abc.es',                'ABC (Spain)',                 87, 'manual'),
  ('lavanguardia.com',      'La Vanguardia',               87, 'manual'),
  ('corriere.it',           'Corriere della Sera',         89, 'manual'),
  ('repubblica.it',         'la Repubblica',               90, 'manual'),
  ('lastampa.it',           'La Stampa',                   86, 'manual'),
  ('ilsole24ore.com',       'Il Sole 24 Ore',              85, 'manual'),
  ('nrc.nl',                'NRC',                         84, 'manual'),
  ('volkskrant.nl',         'de Volkskrant',               84, 'manual'),
  ('ad.nl',                 'AD',                          84, 'manual'),
  ('dn.se',                 'Dagens Nyheter',              82, 'manual'),
  ('svt.se',                'SVT',                         85, 'manual'),
  ('aftenposten.no',        'Aftenposten',                 83, 'manual'),
  ('nrk.no',                'NRK',                         85, 'manual'),
  ('hs.fi',                 'Helsingin Sanomat',           83, 'manual'),
  ('politiken.dk',          'Politiken',                   83, 'manual'),
  ('berlingske.dk',         'Berlingske',                  82, 'manual'),
  -- rte.ie deduped (already inserted above)
  ('euronews.com',          'Euronews',                    89, 'manual'),
  ('politico.eu',           'Politico Europe',             87, 'manual'),
  ('eurozine.com',          'Eurozine',                    72, 'manual'),
  ('sifted.eu',             'Sifted',                      72, 'manual'),
  ('thelocal.com',          'The Local',                   80, 'manual'),

  -- ========== Asia / Middle East / Africa ==========
  ('aljazeera.com',         'Al Jazeera',                  92, 'manual'),
  ('scmp.com',              'South China Morning Post',    91, 'manual'),
  ('japantimes.co.jp',      'The Japan Times',             87, 'manual'),
  ('asahi.com',             'The Asahi Shimbun',           86, 'manual'),
  ('mainichi.jp',           'The Mainichi',                85, 'manual'),
  ('nikkei.com',            'Nikkei',                      87, 'manual'),
  ('asia.nikkei.com',       'Nikkei Asia',                 82, 'manual'),
  ('koreatimes.co.kr',      'The Korea Times',             83, 'manual'),
  ('koreaherald.com',       'The Korea Herald',            83, 'manual'),
  ('chosun.com',            'The Chosun Ilbo',             83, 'manual'),
  ('thehindu.com',          'The Hindu',                   90, 'manual'),
  ('timesofindia.indiatimes.com','The Times of India',     93, 'manual'),
  ('indianexpress.com',     'The Indian Express',          90, 'manual'),
  ('hindustantimes.com',    'Hindustan Times',             90, 'manual'),
  ('ndtv.com',              'NDTV',                        91, 'manual'),
  ('livemint.com',          'Mint',                        87, 'manual'),
  ('economictimes.indiatimes.com','The Economic Times',    91, 'manual'),
  ('business-standard.com', 'Business Standard',           86, 'manual'),
  ('moneycontrol.com',      'Moneycontrol',                88, 'manual'),
  ('straitstimes.com',      'The Straits Times',           88, 'manual'),
  ('channelnewsasia.com',   'CNA',                         88, 'manual'),
  ('bangkokpost.com',       'Bangkok Post',                85, 'manual'),
  ('thejakartapost.com',    'The Jakarta Post',            83, 'manual'),
  ('rappler.com',           'Rappler',                     83, 'manual'),
  ('inquirer.net',          'Philippine Daily Inquirer',   86, 'manual'),
  ('vnexpress.net',         'VnExpress',                   85, 'manual'),
  ('haaretz.com',           'Haaretz',                     86, 'manual'),
  ('timesofisrael.com',     'The Times of Israel',         85, 'manual'),
  ('jpost.com',             'The Jerusalem Post',          86, 'manual'),
  ('thenationalnews.com',   'The National',                81, 'manual'),
  ('gulfnews.com',          'Gulf News',                   85, 'manual'),
  ('arabnews.com',          'Arab News',                   84, 'manual'),
  ('news24.com',            'News24',                      85, 'manual'),
  ('iol.co.za',             'IOL',                         83, 'manual'),
  ('mg.co.za',              'Mail & Guardian',             82, 'manual'),
  ('businesslive.co.za',    'Business Day',                78, 'manual'),
  ('punchng.com',           'The Punch',                   84, 'manual'),
  ('premiumtimesng.com',    'Premium Times',               80, 'manual'),
  ('nation.africa',         'Daily Nation',                82, 'manual'),

  -- ========== Latin America ==========
  ('clarin.com',            'Clarín',                      89, 'manual'),
  ('lanacion.com.ar',       'La Nación',                   88, 'manual'),
  ('infobae.com',           'Infobae',                     90, 'manual'),
  ('folha.uol.com.br',      'Folha de S.Paulo',            89, 'manual'),
  ('estadao.com.br',        'O Estado de S. Paulo',        88, 'manual'),
  ('g1.globo.com',          'G1',                          92, 'manual'),
  ('eluniversal.com.mx',    'El Universal',                86, 'manual'),
  ('milenio.com',           'Milenio',                     85, 'manual'),
  ('reforma.com',           'Reforma',                     82, 'manual'),
  ('eltiempo.com',          'El Tiempo',                   87, 'manual'),
  ('emol.com',              'Emol',                        85, 'manual'),
  ('latercera.com',         'La Tercera',                  84, 'manual'),

  -- ========== Tech / startups / SaaS ==========
  ('theregister.com',       'The Register',                88, 'manual'),
  ('zdnet.com',             'ZDNet',                       91, 'manual'),
  ('cnet.com',              'CNET',                        92, 'manual'),
  ('tomshardware.com',      'Tom''s Hardware',             89, 'manual'),
  ('anandtech.com',         'AnandTech',                   85, 'manual'),
  ('pcmag.com',             'PCMag',                       90, 'manual'),
  ('pcworld.com',           'PCWorld',                     89, 'manual'),
  ('macrumors.com',         'MacRumors',                   90, 'manual'),
  ('9to5mac.com',           '9to5Mac',                     87, 'manual'),
  ('9to5google.com',        '9to5Google',                  85, 'manual'),
  ('appleinsider.com',      'AppleInsider',                85, 'manual'),
  ('androidpolice.com',     'Android Police',              85, 'manual'),
  ('androidauthority.com',  'Android Authority',           86, 'manual'),
  ('xda-developers.com',    'XDA Developers',              85, 'manual'),
  ('techradar.com',         'TechRadar',                   91, 'manual'),
  ('lifehacker.com',        'Lifehacker',                  89, 'manual'),
  ('readwrite.com',         'ReadWrite',                   84, 'manual'),
  ('siliconangle.com',      'SiliconANGLE',                80, 'manual'),
  ('techspot.com',          'TechSpot',                    84, 'manual'),
  ('slashdot.org',          'Slashdot',                    88, 'manual'),
  ('hackernoon.com',        'HackerNoon',                  84, 'manual'),
  ('news.ycombinator.com',  'Hacker News',                 91, 'manual'),
  ('producthunt.com',       'Product Hunt',                90, 'manual'),
  ('crunchbase.com',        'Crunchbase News',             89, 'manual'),
  ('news.crunchbase.com',   'Crunchbase News',             80, 'manual'),
  ('pitchbook.com',         'PitchBook News',              82, 'manual'),
  ('cbinsights.com',        'CB Insights',                 84, 'manual'),
  ('a16z.com',              'a16z',                        85, 'manual'),
  ('stratechery.com',       'Stratechery',                 80, 'manual'),
  ('platformer.news',       'Platformer',                  72, 'manual'),
  ('techmeme.com',          'Techmeme',                    87, 'manual'),
  ('geekwire.com',          'GeekWire',                    81, 'manual'),
  ('builtin.com',           'Built In',                    81, 'manual'),
  ('eu-startups.com',       'EU-Startups',                 75, 'manual'),
  ('tech.eu',               'Tech.eu',                     74, 'manual'),
  ('techcabal.com',         'TechCabal',                   72, 'manual'),
  ('rest-of-world.com',     'Rest of World',               75, 'manual'),
  ('restofworld.org',       'Rest of World',               75, 'manual'),
  ('404media.co',           '404 Media',                   72, 'manual'),
  ('theverge.com',          'The Verge',                   92, 'manual'),
  ('decoder.ai',            'Decoder',                     50, 'manual'),
  ('aibusiness.com',        'AI Business',                 70, 'manual'),
  ('marktechpost.com',      'MarkTechPost',                72, 'manual'),
  ('thealgorithmicbridge.com','The Algorithmic Bridge',    55, 'manual'),
  ('importai.substack.com', 'Import AI',                   55, 'manual'),

  -- ========== Business / finance ==========
  ('seekingalpha.com',      'Seeking Alpha',               90, 'manual'),
  ('investopedia.com',      'Investopedia',                93, 'manual'),
  ('fool.com',              'The Motley Fool',             90, 'manual'),
  ('benzinga.com',          'Benzinga',                    87, 'manual'),
  ('businesswire.com',      'Business Wire',               92, 'manual'),
  ('prnewswire.com',        'PR Newswire',                 92, 'manual'),
  ('globenewswire.com',     'GlobeNewswire',               90, 'manual'),
  ('reuters.com',           'Reuters',                     93, 'manual'),
  ('finance.yahoo.com',     'Yahoo Finance',               94, 'manual'),
  ('morningstar.com',       'Morningstar',                 90, 'manual'),
  ('investors.com',         'Investor''s Business Daily',  87, 'manual'),
  ('thestreet.com',         'TheStreet',                   89, 'manual'),
  ('kiplinger.com',         'Kiplinger',                   89, 'manual'),
  ('moneywise.com',         'Moneywise',                   76, 'manual'),
  ('nerdwallet.com',        'NerdWallet',                  90, 'manual'),
  ('coindesk.com',          'CoinDesk',                    90, 'manual'),
  ('cointelegraph.com',     'Cointelegraph',               89, 'manual'),
  ('decrypt.co',            'Decrypt',                     83, 'manual'),
  ('theblock.co',           'The Block',                   80, 'manual'),
  ('blockworks.co',         'Blockworks',                  74, 'manual'),
  ('protos.com',            'Protos',                      66, 'manual'),

  -- ========== Marketing / PR / advertising ==========
  ('adage.com',             'Ad Age',                      87, 'manual'),
  ('mediapost.com',         'MediaPost',                   83, 'manual'),
  ('marketingdive.com',     'Marketing Dive',              78, 'manual'),
  ('searchengineland.com',  'Search Engine Land',          88, 'manual'),
  ('searchenginejournal.com','Search Engine Journal',      87, 'manual'),
  ('moz.com',               'Moz Blog',                    93, 'manual'),
  ('semrush.com',           'Semrush Blog',                92, 'manual'),
  ('ahrefs.com',            'Ahrefs Blog',                 90, 'manual'),
  ('hubspot.com',           'HubSpot Blog',                93, 'manual'),
  ('contentmarketinginstitute.com','Content Marketing Institute',82,'manual'),
  ('socialmediaexaminer.com','Social Media Examiner',      85, 'manual'),
  ('socialmediatoday.com',  'Social Media Today',          84, 'manual'),
  ('thedrum.com',           'The Drum',                    85, 'manual'),
  ('cmswire.com',           'CMSWire',                     78, 'manual'),
  ('odwyerpr.com',          'O''Dwyer''s',                 65, 'manual'),
  ('bulldogreporter.com',   'Bulldog Reporter',            58, 'manual'),
  ('prdaily.com',           'PR Daily',                    74, 'manual'),
  ('prnews.io',             'PRNEWS.IO',                   65, 'manual'),
  ('musebycl.io',           'Muse by Clio',                70, 'manual'),
  ('clios.com',             'Clio Awards',                 67, 'manual'),

  -- ========== Lifestyle / culture / fashion ==========
  ('refinery29.com',        'Refinery29',                  89, 'manual'),
  ('bustle.com',            'Bustle',                      88, 'manual'),
  ('cosmopolitan.com',      'Cosmopolitan',                90, 'manual'),
  ('marieclaire.com',       'Marie Claire',                89, 'manual'),
  ('harpersbazaar.com',     'Harper''s Bazaar',            89, 'manual'),
  ('glamour.com',           'Glamour',                     89, 'manual'),
  ('instyle.com',           'InStyle',                     88, 'manual'),
  ('allure.com',            'Allure',                      88, 'manual'),
  ('teenvogue.com',         'Teen Vogue',                  87, 'manual'),
  ('wmagazine.com',         'W Magazine',                  85, 'manual'),
  ('vanityfair.com',        'Vanity Fair',                 91, 'manual'),
  ('thecut.com',            'The Cut',                     87, 'manual'),
  ('nymag.com',             'New York Magazine',           90, 'manual'),
  ('bonappetit.com',        'Bon Appétit',                 89, 'manual'),
  ('eater.com',             'Eater',                       88, 'manual'),
  ('foodandwine.com',       'Food & Wine',                 87, 'manual'),
  ('saveur.com',            'Saveur',                      80, 'manual'),
  ('seriouseats.com',       'Serious Eats',                86, 'manual'),
  ('thekitchn.com',         'The Kitchn',                  87, 'manual'),
  ('epicurious.com',        'Epicurious',                  88, 'manual'),
  ('marthastewart.com',     'Martha Stewart',              87, 'manual'),
  ('apartmenttherapy.com',  'Apartment Therapy',           88, 'manual'),
  ('architecturaldigest.com','Architectural Digest',       89, 'manual'),
  ('dezeen.com',            'Dezeen',                      88, 'manual'),
  ('designboom.com',        'Designboom',                  86, 'manual'),
  ('dwell.com',             'Dwell',                       82, 'manual'),
  ('elledecor.com',         'Elle Decor',                  85, 'manual'),
  ('housebeautiful.com',    'House Beautiful',             86, 'manual'),
  ('hgtv.com',              'HGTV',                        90, 'manual'),
  ('thespruce.com',         'The Spruce',                  88, 'manual'),
  ('countryliving.com',     'Country Living',              86, 'manual'),
  ('travelandleisure.com',  'Travel + Leisure',            88, 'manual'),
  ('cntraveler.com',        'Condé Nast Traveler',         89, 'manual'),
  ('afar.com',              'AFAR',                        81, 'manual'),
  ('lonelyplanet.com',      'Lonely Planet',               91, 'manual'),
  ('nationalgeographic.com','National Geographic',         93, 'manual'),
  ('smithsonianmag.com',    'Smithsonian Magazine',        91, 'manual'),

  -- ========== Entertainment / film / music ==========
  ('deadline.com',          'Deadline',                    90, 'manual'),
  ('indiewire.com',          'IndieWire',                  86, 'manual'),
  ('ew.com',                'Entertainment Weekly',        90, 'manual'),
  ('people.com',            'People',                      93, 'manual'),
  ('usmagazine.com',        'Us Weekly',                   90, 'manual'),
  ('tmz.com',               'TMZ',                         90, 'manual'),
  ('eonline.com',           'E! News',                     90, 'manual'),
  ('avclub.com',            'The A.V. Club',               87, 'manual'),
  ('vulture.com',           'Vulture',                     86, 'manual'),
  ('collider.com',          'Collider',                    87, 'manual'),
  ('slashfilm.com',         '/Film',                       82, 'manual'),
  ('screenrant.com',        'Screen Rant',                 88, 'manual'),
  ('comingsoon.net',        'ComingSoon.net',              82, 'manual'),
  ('empireonline.com',      'Empire',                      85, 'manual'),
  ('totalfilm.com',         'Total Film',                  78, 'manual'),
  ('pitchfork.com',         'Pitchfork',                   89, 'manual'),
  ('nme.com',               'NME',                         88, 'manual'),
  ('stereogum.com',         'Stereogum',                   83, 'manual'),
  ('consequence.net',       'Consequence',                 80, 'manual'),
  ('spin.com',              'SPIN',                        84, 'manual'),
  ('kerrang.com',           'Kerrang!',                    80, 'manual'),
  ('loudwire.com',          'Loudwire',                    78, 'manual'),
  ('xxlmag.com',            'XXL',                         85, 'manual'),
  ('complex.com',           'Complex',                     90, 'manual'),
  ('hotnewhiphop.com',      'HotNewHipHop',                82, 'manual'),
  ('hypebeast.com',         'Hypebeast',                   89, 'manual'),
  ('highsnobiety.com',      'Highsnobiety',                86, 'manual'),

  -- ========== Sports ==========
  ('espn.com',              'ESPN',                        94, 'manual'),
  ('si.com',                'Sports Illustrated',          92, 'manual'),
  ('cbssports.com',         'CBS Sports',                  92, 'manual'),
  ('nbcsports.com',         'NBC Sports',                  90, 'manual'),
  ('foxsports.com',         'FOX Sports',                  90, 'manual'),
  ('bleacherreport.com',    'Bleacher Report',             92, 'manual'),
  ('theathletic.com',       'The Athletic',                86, 'manual'),
  ('sbnation.com',          'SB Nation',                   88, 'manual'),
  ('deadspin.com',          'Deadspin',                    87, 'manual'),
  ('theringer.com',         'The Ringer',                  85, 'manual'),
  ('sports.yahoo.com',      'Yahoo Sports',                92, 'manual'),
  ('skysports.com',         'Sky Sports',                  90, 'manual'),
  ('bbc.com/sport',         'BBC Sport',                   93, 'manual'),
  ('goal.com',              'Goal.com',                    91, 'manual'),
  ('espnfc.com',            'ESPN FC',                     86, 'manual'),
  ('marca.com',             'Marca',                       89, 'manual'),
  ('lequipe.fr',            'L''Équipe',                   88, 'manual'),
  ('gazzetta.it',           'La Gazzetta dello Sport',     87, 'manual'),
  ('formula1.com',          'Formula 1',                   88, 'manual'),
  ('motorsport.com',        'Motorsport.com',              85, 'manual'),
  ('autosport.com',         'Autosport',                   84, 'manual'),
  ('cyclingnews.com',       'Cyclingnews',                 80, 'manual'),
  ('golfdigest.com',        'Golf Digest',                 86, 'manual'),
  ('golf.com',              'Golf.com',                    81, 'manual'),
  ('tennis.com',            'Tennis.com',                  81, 'manual'),
  ('mma.com',               'MMA.com',                     65, 'manual'),
  ('mmafighting.com',       'MMA Fighting',                83, 'manual'),
  ('mmajunkie.usatoday.com','MMA Junkie',                  82, 'manual'),

  -- ========== Health / science ==========
  ('webmd.com',             'WebMD',                       93, 'manual'),
  ('healthline.com',        'Healthline',                  92, 'manual'),
  ('mayoclinic.org',        'Mayo Clinic',                 93, 'manual'),
  ('medicalnewstoday.com',  'Medical News Today',          90, 'manual'),
  ('statnews.com',          'STAT News',                   85, 'manual'),
  ('medpagetoday.com',      'MedPage Today',               82, 'manual'),
  ('nejm.org',              'NEJM',                        93, 'manual'),
  ('thelancet.com',         'The Lancet',                  93, 'manual'),
  ('nature.com',            'Nature',                      94, 'manual'),
  ('science.org',           'Science',                     93, 'manual'),
  ('sciencemag.org',        'Science Magazine',            91, 'manual'),
  ('scientificamerican.com','Scientific American',         93, 'manual'),
  ('newscientist.com',      'New Scientist',               91, 'manual'),
  ('popsci.com',            'Popular Science',             90, 'manual'),
  ('popularmechanics.com',  'Popular Mechanics',           90, 'manual'),
  ('discovermagazine.com',  'Discover Magazine',           86, 'manual'),
  ('phys.org',              'Phys.org',                    89, 'manual'),
  ('livescience.com',       'Live Science',                90, 'manual'),
  ('space.com',             'Space.com',                   91, 'manual'),
  ('sciencenews.org',       'Science News',                85, 'manual'),
  ('quantamagazine.org',    'Quanta Magazine',             82, 'manual'),
  ('undark.org',            'Undark',                      72, 'manual'),
  ('mit.edu',               'MIT News',                    93, 'manual'),
  ('news.mit.edu',          'MIT News',                    87, 'manual'),
  ('technologyreview.com',  'MIT Technology Review',       90, 'manual'),
  ('ieee.org',              'IEEE Spectrum',               90, 'manual'),
  ('spectrum.ieee.org',     'IEEE Spectrum',               86, 'manual'),
  ('arstechnica.com',       'Ars Technica',                90, 'manual'),

  -- ========== Climate / sustainability ==========
  ('grist.org',             'Grist',                       82, 'manual'),
  ('insideclimatenews.org', 'Inside Climate News',         78, 'manual'),
  ('climatewire.org',       'Climatewire',                 60, 'manual'),
  ('cleantechnica.com',     'CleanTechnica',               86, 'manual'),
  ('greentechmedia.com',    'Greentech Media',             80, 'manual'),
  ('canarymedia.com',       'Canary Media',                70, 'manual'),
  ('treehugger.com',        'Treehugger',                  86, 'manual'),
  ('mongabay.com',          'Mongabay',                    85, 'manual'),
  ('e360.yale.edu',         'Yale Environment 360',        78, 'manual'),

  -- ========== Education / academia / kids ==========
  ('edweek.org',            'Education Week',              82, 'manual'),
  ('insidehighered.com',    'Inside Higher Ed',            83, 'manual'),
  ('chronicle.com',         'The Chronicle of Higher Education',85,'manual'),
  ('timeshighereducation.com','Times Higher Education',    83, 'manual'),
  ('edsurge.com',           'EdSurge',                     78, 'manual'),
  ('the74million.org',      'The 74',                      72, 'manual'),
  ('chalkbeat.org',         'Chalkbeat',                   75, 'manual'),
  ('hechingerreport.org',   'The Hechinger Report',        72, 'manual'),

  -- ========== Gaming ==========
  ('ign.com',               'IGN',                         92, 'manual'),
  ('gamespot.com',          'GameSpot',                    91, 'manual'),
  ('polygon.com',           'Polygon',                     90, 'manual'),
  ('kotaku.com',            'Kotaku',                      90, 'manual'),
  ('eurogamer.net',         'Eurogamer',                   88, 'manual'),
  ('rockpapershotgun.com',  'Rock Paper Shotgun',          85, 'manual'),
  ('pcgamer.com',           'PC Gamer',                    89, 'manual'),
  ('destructoid.com',       'Destructoid',                 83, 'manual'),
  ('gameinformer.com',      'Game Informer',               86, 'manual'),
  ('nintendolife.com',      'Nintendo Life',               83, 'manual'),
  ('pushsquare.com',        'Push Square',                 80, 'manual'),
  ('venturebeat.com',       'VentureBeat',                 89, 'manual'),

  -- ========== Industry trade pubs ==========
  ('autonews.com',          'Automotive News',             82, 'manual'),
  ('motortrend.com',        'MotorTrend',                  88, 'manual'),
  ('caranddriver.com',      'Car and Driver',              89, 'manual'),
  ('roadandtrack.com',      'Road & Track',                86, 'manual'),
  ('jalopnik.com',           'Jalopnik',                   88, 'manual'),
  ('electrek.co',           'Electrek',                    84, 'manual'),
  ('insideevs.com',         'InsideEVs',                   80, 'manual'),
  ('autoblog.com',          'Autoblog',                    87, 'manual'),
  ('hospitalitydesign.com', 'Hospitality Design',          65, 'manual'),
  ('hotelmanagement.net',   'Hotel Management',            70, 'manual'),
  ('skift.com',             'Skift',                       82, 'manual'),
  ('phocuswire.com',        'PhocusWire',                  72, 'manual'),
  ('thefashionspot.com',    'theFashionSpot',              78, 'manual'),
  ('businessoffashion.com', 'Business of Fashion',         84, 'manual'),
  ('wwd.com',               'WWD',                         86, 'manual'),
  ('retaildive.com',        'Retail Dive',                 78, 'manual'),
  ('chainstoreage.com',     'Chain Store Age',             72, 'manual'),
  ('modernretail.co',       'Modern Retail',               72, 'manual'),
  ('foodbusinessnews.net',  'Food Business News',          72, 'manual'),
  ('fooddive.com',          'Food Dive',                   75, 'manual'),
  ('grocerydive.com',       'Grocery Dive',                70, 'manual'),
  ('restaurantbusinessonline.com','Restaurant Business',   72, 'manual'),
  ('nrn.com',               'Nation''s Restaurant News',   75, 'manual'),
  ('progressivegrocer.com', 'Progressive Grocer',          72, 'manual'),
  ('supermarketnews.com',   'Supermarket News',            72, 'manual'),
  ('constructiondive.com',  'Construction Dive',           74, 'manual'),
  ('enr.com',               'Engineering News-Record',     78, 'manual'),
  ('archdaily.com',         'ArchDaily',                   91, 'manual'),
  ('inman.com',             'Inman',                       80, 'manual'),
  ('therealdeal.com',       'The Real Deal',               80, 'manual'),
  ('bisnow.com',            'Bisnow',                      80, 'manual'),
  ('housingwire.com',       'HousingWire',                 78, 'manual'),
  ('mortgagenewsdaily.com', 'Mortgage News Daily',         82, 'manual'),
  ('americanbanker.com',    'American Banker',             82, 'manual'),
  ('finextra.com',          'Finextra',                    78, 'manual'),
  ('paymentsdive.com',      'Payments Dive',               68, 'manual'),
  ('insurancejournal.com',  'Insurance Journal',           75, 'manual'),
  ('healthcaredive.com',    'Healthcare Dive',             78, 'manual'),
  ('fiercehealthcare.com',  'Fierce Healthcare',           78, 'manual'),
  ('fiercebiotech.com',     'Fierce Biotech',              78, 'manual'),
  ('fiercepharma.com',      'Fierce Pharma',               78, 'manual'),
  ('endpts.com',            'Endpoints News',              74, 'manual'),
  ('biopharmadive.com',     'BioPharma Dive',              74, 'manual'),
  ('beckershospitalreview.com','Becker''s Hospital Review',80, 'manual'),
  ('modernhealthcare.com',  'Modern Healthcare',           80, 'manual'),
  ('law360.com',            'Law360',                      80, 'manual'),
  ('abovethelaw.com',       'Above the Law',               80, 'manual'),
  ('americanlawyer.com',    'The American Lawyer',         72, 'manual'),
  ('hrdive.com',            'HR Dive',                     72, 'manual'),
  ('shrm.org',              'SHRM',                        88, 'manual'),
  ('logisticsmgmt.com',     'Logistics Management',        70, 'manual'),
  ('supplychaindive.com',   'Supply Chain Dive',           74, 'manual'),
  ('freightwaves.com',      'FreightWaves',                75, 'manual'),
  ('aviationweek.com',      'Aviation Week',               80, 'manual'),
  ('flightglobal.com',      'FlightGlobal',                80, 'manual'),
  ('simpleflying.com',      'Simple Flying',               82, 'manual'),
  ('ag.com',                'Ag.com',                      55, 'manual'),
  ('agriculture.com',       'Agriculture.com',             78, 'manual'),
  ('agweb.com',             'AgWeb',                       72, 'manual'),
  ('utilitydive.com',       'Utility Dive',                78, 'manual'),
  ('rigzone.com',           'Rigzone',                     77, 'manual'),
  ('oilprice.com',          'Oilprice.com',                86, 'manual'),
  ('miningweekly.com',      'Mining Weekly',               72, 'manual'),
  ('cio.com',               'CIO',                         88, 'manual'),
  ('csoonline.com',         'CSO Online',                  84, 'manual'),
  ('darkreading.com',       'Dark Reading',                82, 'manual'),
  ('bleepingcomputer.com',  'BleepingComputer',            87, 'manual'),
  ('threatpost.com',        'Threatpost',                  82, 'manual'),
  ('krebsonsecurity.com',   'Krebs on Security',           82, 'manual'),
  ('thehackernews.com',     'The Hacker News',             89, 'manual'),
  ('securityweek.com',      'SecurityWeek',                80, 'manual'),
  ('infosecurity-magazine.com','Infosecurity Magazine',    78, 'manual'),
  ('computerweekly.com',    'ComputerWeekly',              86, 'manual'),
  ('infoworld.com',         'InfoWorld',                   85, 'manual'),
  ('networkworld.com',      'Network World',               84, 'manual'),
  ('techtarget.com',        'TechTarget',                  90, 'manual'),
  ('itpro.com',             'ITPro',                       82, 'manual'),
  ('itpro.co.uk',           'ITPro UK',                    80, 'manual'),
  ('diginomica.com',        'Diginomica',                  72, 'manual'),
  ('protocol.com',          'Protocol',                    82, 'manual'),

  -- ========== Opinion / longform / culture ==========
  ('aeon.co',               'Aeon',                        82, 'manual'),
  ('thebaffler.com',        'The Baffler',                 76, 'manual'),
  ('lithub.com',            'Literary Hub',                80, 'manual'),
  ('lrb.co.uk',             'London Review of Books',      82, 'manual'),
  ('nybooks.com',           'The New York Review of Books',86, 'manual'),
  ('theparisreview.org',    'The Paris Review',            82, 'manual'),
  ('harpers.org',           'Harper''s Magazine',          85, 'manual'),
  -- thecut.com deduped (already inserted above)
  ('jacobinmag.com',        'Jacobin',                     83, 'manual'),
  ('jacobin.com',           'Jacobin',                     83, 'manual'),
  ('reason.com',            'Reason',                      85, 'manual'),
  ('nationalreview.com',    'National Review',             86, 'manual'),
  ('thefederalist.com',     'The Federalist',              82, 'manual'),
  ('washingtonexaminer.com','Washington Examiner',         85, 'manual'),
  ('thebulwark.com',        'The Bulwark',                 75, 'manual')

on conflict (domain) do update
  set authority_score = excluded.authority_score,
      outlet_name     = excluded.outlet_name,
      source          = excluded.source,
      updated_at      = now();

-- ============================================================
-- Verify count
-- select count(*) as total_outlets,
--        count(*) filter (where source = 'manual') as manual,
--        count(*) filter (where source = 'ahrefs') as ahrefs
--   from public.outlet_authority;
-- ============================================================
